import { StyleSheet } from "react-native";
import { createCardSurface, ui, withAlpha } from "./_utils/designSystem";
import type { ThemeColors } from "./_utils/themeContext";

export const createStyles = (colors: ThemeColors) => {
  const headerDividerColor = colors.divider;
  const cardSurface = createCardSurface(colors, {
    padding: ui.spacing.card,
    radius: ui.radius.card,
  });

  const secondaryCardSurface = createCardSurface(colors, {
    padding: ui.spacing.card,
    radius: ui.radius.card,
    glowOpacity: 0.06,
    borderOpacity: ui.border.opacitySecondary,
    backgroundColor: colors.surface2,
  });

  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.bg },
    screen: { flex: 1, backgroundColor: colors.bg },
    bgArt: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    sectionBand: {
      paddingHorizontal: ui.spacing.xs,
      paddingVertical: ui.spacing.md,
    },
    sectionBandTight: {
      paddingBottom: ui.spacing.sm,
    },
    container: { paddingHorizontal: ui.spacing.screen, paddingTop: ui.spacing.screen, paddingBottom: ui.spacing.xl },

    title: {
      ...ui.typography.title,
      color: colors.accentPrimary,
      marginBottom: 0,
      fontSize: 22,
      lineHeight: 26,
      fontWeight: "900",
      letterSpacing: 1.2,
    },
    homeSubtitle: {
      color: colors.textSecondary,
      fontSize: ui.typography.caption.fontSize,
      fontWeight: "600",
      marginTop: 0,
      marginBottom: 0,
      lineHeight: ui.typography.caption.lineHeight,
      letterSpacing: ui.typography.caption.letterSpacing,
    },
    homeTopBar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-end",
      marginBottom: ui.spacing.md,
      paddingBottom: ui.spacing.xs,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider,
    },
    statusHeader: {
      backgroundColor: withAlpha(colors.surface2, 0.3),
      borderWidth: 1,
      borderColor: colors.cardBorder,
      borderRadius: 14,
      paddingHorizontal: ui.spacing.md,
      paddingTop: ui.spacing.lg,
      paddingBottom: ui.spacing.lg,
      gap: ui.spacing.lg,
    },
    statusHeaderTop: {
      flexDirection: "row",
      alignItems: "center",
      gap: ui.spacing.lg + ui.spacing.xxs,
      paddingBottom: ui.spacing.md + ui.spacing.xs,
      borderBottomWidth: 1,
      borderBottomColor: headerDividerColor,
    },
    rankBadgeRail: {
      width: 44,
      height: 44,
      borderWidth: 1,
      borderColor: colors.cardBorder,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "center",
      transform: [{ translateY: 2 }],
      backgroundColor: withAlpha(colors.surface, 0.18),
    },
    statusHeaderMain: {
      flex: 1,
      gap: ui.spacing.sm,
      justifyContent: "center",
    },
    statusLabel: {
      ...ui.typography.caption,
      color: colors.textTertiary,
      fontSize: 10,
      letterSpacing: 0.7,
    },
    statusDrValue: {
      ...ui.typography.drHero,
      color: colors.textPrimary,
      fontSize: 60,
      lineHeight: 62,
      fontWeight: "900",
      marginTop: 6,
    },
    statusRankRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: ui.spacing.sm,
      marginTop: ui.spacing.xs,
    },
    statusRankName: {
      fontSize: 13,
      fontWeight: "900",
      letterSpacing: 0.4,
      color: colors.textPrimary,
    },
    statusRankNext: {
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.35,
      color: colors.textSecondary,
    },
    midnightStrip: {
      flexDirection: "row",
      alignItems: "flex-start",
      borderBottomWidth: 1,
      borderColor: headerDividerColor,
      paddingVertical: ui.spacing.md + ui.spacing.xs,
    },
    midnightCell: {
      flex: 1,
      gap: ui.spacing.sm,
      paddingRight: ui.spacing.sm,
    },
    midnightCellRight: {
      alignItems: "flex-end",
      borderLeftWidth: 0,
      paddingLeft: ui.spacing.sm,
      paddingRight: 0,
    },
    midnightLabel: {
      ...ui.typography.caption,
      color: colors.textTertiary,
      fontSize: 10,
      letterSpacing: 0.7,
    },
    midnightValue: {
      ...ui.typography.mono,
      color: colors.textPrimary,
      fontSize: 18,
      lineHeight: 24,
      fontWeight: "800",
    },
    midnightUpdateValue: {
      ...ui.typography.mono,
      color: colors.textPrimary,
      fontSize: 24,
      lineHeight: 24,
      fontWeight: "900",
    },
    progressMicroRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: ui.spacing.sm,
      paddingTop: ui.spacing.md + ui.spacing.xs,
    },
    progressMicroItem: {
      flex: 1,
      borderWidth: 0,
      borderRadius: 0,
      paddingVertical: ui.spacing.xs,
      paddingHorizontal: ui.spacing.sm,
      backgroundColor: "transparent",
    },
    progressMicroItemRight: {
      borderLeftWidth: 0,
    },
    progressMicroLabel: {
      ...ui.typography.caption,
      color: colors.textTertiary,
      fontSize: 10,
      letterSpacing: 0.7,
    },
    progressMicroValue: {
      fontSize: 16,
      lineHeight: 20,
      fontWeight: "800",
      color: colors.textPrimary,
      marginTop: 2,
    },
    devActionChip: {
      marginTop: ui.spacing.xs,
      alignSelf: "flex-start",
      borderWidth: 1,
      borderColor: colors.negative,
      borderRadius: ui.radius.sm,
      paddingVertical: ui.spacing.xxs,
      paddingHorizontal: ui.spacing.sm,
    },
    devActionRow: {
      flexDirection: "row",
      gap: ui.spacing.xs,
      marginTop: ui.spacing.xs,
    },
    devActionText: {
      ...ui.typography.caption,
      color: colors.negative,
      fontSize: 10,
      letterSpacing: 0.6,
    },

    topRow: { flexDirection: "row", gap: 10, marginBottom: ui.spacing.md, flexWrap: "wrap" },
    pill: {
      backgroundColor: colors.surface,
      borderRadius: ui.radius.card,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderWidth: ui.border.width,
      borderColor: withAlpha(colors.border, ui.border.opacityCard),
      flex: 1,
      minWidth: 110,
      shadowColor: colors.text,
      shadowOffset: ui.shadow.soft.shadowOffset,
      shadowOpacity: ui.shadow.soft.shadowOpacity,
      shadowRadius: ui.shadow.soft.shadowRadius,
      elevation: ui.shadow.soft.elevation,
    },
    todayPill: {
      backgroundColor: colors.bg,
      position: "relative",
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 10,
    },
    pillLabel: { color: colors.textSecondary, fontSize: 10, fontWeight: "600", letterSpacing: 0.3, textTransform: "uppercase" },
    pillValue: { color: colors.accentPrimary, fontSize: 15, fontWeight: "900", marginTop: 3, letterSpacing: 0.3 },
    drPrimaryPill: {
      width: "100%",
      flexBasis: "100%",
      minWidth: "100%",
      paddingVertical: ui.spacing.xl,
      paddingHorizontal: ui.spacing.md,
      borderWidth: ui.border.width,
      alignItems: "center",
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.05,
      shadowRadius: 6,
      elevation: 1,
    },
    drPrimaryValue: {
      ...ui.typography.drHero,
      fontSize: 60,
      lineHeight: 64,
      marginTop: ui.spacing.sm,
      marginBottom: ui.spacing.xs,
      textAlign: "center",
      textShadowColor: withAlpha(colors.accentPrimary, 0.28),
      textShadowOffset: { width: 0, height: 0 },
      textShadowRadius: 9,
    },
    drRankText: {
      marginTop: ui.spacing.xs,
      fontSize: 14,
      fontWeight: "800",
      letterSpacing: 0.2,
      textAlign: "center",
    },
    drSupportText: {
      textAlign: "center",
      marginTop: ui.spacing.xs,
      fontSize: ui.typography.body.fontSize,
      lineHeight: ui.typography.body.lineHeight,
      opacity: 0.86,
    },
    drProgressBlock: {
      width: "100%",
      marginTop: 12,
      alignItems: "center",
    },
    drProgressTrack: {
      width: "100%",
      height: 8,
      borderRadius: 999,
      borderWidth: 1,
      overflow: "hidden",
    },
    drProgressFill: {
      height: "100%",
      borderRadius: 999,
    },
    drProgressText: {
      marginTop: 6,
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    drLabelText: {
      fontSize: 13,
      fontWeight: "800",
      letterSpacing: 0.35,
      textTransform: "uppercase",
    },
    secondaryPillLabel: {
      fontSize: 9,
      opacity: 0.75,
    },
    secondaryPillValue: {
      fontSize: 13,
      marginTop: 2,
      opacity: 0.85,
    },
    todayLabelRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
    todayAccentDot: { width: 6, height: 6, borderRadius: 999 },
    todayContent: { zIndex: 1, alignItems: "center" },
    todayRingWrap: { position: "absolute", zIndex: 0 },
    todayXPRow: {
      alignSelf: "center",
      backgroundColor: `${colors.accentPrimary}1A`,
      borderRadius: 9,
      paddingVertical: 4,
      paddingHorizontal: 8,
      marginTop: 6,
    },
    todayValue: {
      fontSize: 14,
      textShadowColor: colors.accentPrimary,
      textShadowOffset: { width: 0, height: 0 },
      textShadowRadius: 6,
    },
    todaySummaryCard: {
      marginTop: ui.spacing.md,
      borderRadius: ui.radius.card,
      borderWidth: 0,
      paddingVertical: ui.spacing.md,
      paddingHorizontal: ui.spacing.md,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    todaySummaryLabel: {
      fontSize: 11,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.3,
    },
    todaySummaryValue: {
      fontSize: 13,
      fontWeight: "800",
    },

    row: { flexDirection: "row", gap: 10, marginBottom: ui.spacing.md, flexWrap: "wrap" },
    homeActionRow: { flexDirection: "row", gap: ui.spacing.sm, marginTop: ui.spacing.md, marginBottom: 0 },
    btn: {
      backgroundColor: colors.surface,
      paddingVertical: 11,
      paddingHorizontal: 14,
      borderRadius: 11,
      borderWidth: 1.5,
      borderColor: colors.border,
      shadowColor: "rgba(0,0,0,0.2)",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 3,
    },
    btnDanger: {
      backgroundColor: colors.bg,
      paddingVertical: 11,
      paddingHorizontal: 14,
      borderRadius: 11,
      borderWidth: 1.5,
      borderColor: colors.accentPrimary,
      shadowColor: "rgba(0,0,0,0.2)",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 3,
    },
    btnText: { color: colors.textPrimary, fontWeight: "800", fontSize: 12 },
    homeActionBtn: {
      flex: 1,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: ui.border.widthStrong,
      borderRadius: ui.radius.lg,
      paddingVertical: 12,
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "rgba(0,0,0,0.2)",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 3,
    },
    homeActionBtnDanger: {
      flex: 1,
      backgroundColor: colors.bg,
      borderColor: colors.accentPrimary,
      borderWidth: ui.border.widthStrong,
      borderRadius: ui.radius.lg,
      paddingVertical: 12,
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "rgba(0,0,0,0.2)",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 3,
    },
    homeActionText: { color: colors.textPrimary, fontWeight: "900", fontSize: 12, letterSpacing: 0.2 },

    sectionRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: ui.spacing.xs,
      marginTop: ui.spacing.sm,
    },
    section: { ...ui.typography.heading, color: colors.textPrimary },
    sectionSecondary: {
      ...ui.typography.caption,
      color: withAlpha(colors.textSecondary, 0.82),
      textTransform: "uppercase",
      letterSpacing: 0.4,
      marginBottom: ui.spacing.sm,
    },
    sectionSubtext: {
      color: withAlpha(colors.textSecondary, 0.85),
      fontSize: ui.typography.body.fontSize,
      lineHeight: ui.typography.body.lineHeight,
      marginBottom: ui.spacing.sm,
      marginTop: 0,
    },
    link: { color: colors.accentPrimary, fontWeight: "900", fontSize: 12 },

    addBox: {
      ...cardSurface,
      marginBottom: ui.spacing.md,
      gap: ui.spacing.sm,
    },
    input: {
      backgroundColor: colors.bg,
      color: colors.textPrimary,
      padding: 12,
      borderRadius: 11,
      borderWidth: 1.5,
      borderColor: colors.border,
      fontSize: 14,
      fontWeight: "500",
    },
    inputFocused: {
      borderColor: colors.accentPrimary,
      backgroundColor: colors.surface,
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    smallLabel: { color: colors.textSecondary, fontWeight: "700", fontSize: 11, letterSpacing: 0.2 },

    pickerRow: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
    pillPick: {
      paddingVertical: 9,
      paddingHorizontal: 11,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.bg,
    },
    pillPickActive: { backgroundColor: colors.accentPrimary, borderColor: colors.accentPrimary },
    pillPickText: { color: colors.textSecondary, fontWeight: "800", fontSize: 11 },
    pillPickTextActive: { color: colors.textPrimary, fontWeight: "900" },

    addBtn: {
      backgroundColor: colors.accentPrimary,
      padding: 13,
      borderRadius: 11,
      alignItems: "center",
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
    },
    addBtnText: { color: colors.textPrimary, fontWeight: "900", fontSize: 13 },

    editSheetModalRoot: {
      flex: 1,
      justifyContent: "flex-end",
    },
    editSheetBackdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    editSheetKeyboardWrap: {
      justifyContent: "flex-end",
    },
    editSheetContainer: {
      width: "100%",
      maxHeight: "85%",
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      borderWidth: 1,
      borderBottomWidth: 0,
      overflow: "hidden",
    },
    editSheetHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderBottomWidth: 1,
    },
    editSheetTitle: {
      fontSize: 20,
      lineHeight: 24,
      fontWeight: "900",
      letterSpacing: 0.3,
    },
    editSheetCloseButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    editSheetCloseText: {
      fontSize: 22,
      lineHeight: 22,
      fontWeight: "500",
      marginTop: -2,
    },
    editSheetScroll: {
      flexGrow: 0,
    },
    editSheetFormContent: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 24,
      gap: 16,
    },
    editSheetFieldBlock: {
      gap: 8,
    },
    editSheetLabel: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    editSheetInput: {
      minHeight: 48,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 12,
      borderWidth: 0,
      fontSize: 15,
      fontWeight: "500",
    },
    editSheetChipRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    editSheetDifficultyRow: {
      flexDirection: "row",
      gap: 8,
    },
    editSheetChip: {
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      minHeight: 40,
      justifyContent: "center",
      borderWidth: 1,
    },
    editSheetDifficultyChip: {
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      minHeight: 40,
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
    },
    editSheetChipText: {
      fontSize: 13,
      lineHeight: 16,
      fontWeight: "800",
    },
    editSheetActionBar: {
      borderTopWidth: 1,
      paddingHorizontal: 16,
      paddingVertical: 12,
      paddingBottom: 16,
    },
    editSheetPrimaryButton: {
      minHeight: 48,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 16,
    },
    editSheetPrimaryButtonText: {
      fontSize: 14,
      lineHeight: 18,
      fontWeight: "900",
      letterSpacing: 0.2,
    },

    list: { gap: 0, marginBottom: ui.spacing.md },
    questCard: {
      backgroundColor: "transparent",
      borderBottomWidth: 1,
      borderRadius: 0,
      borderColor: withAlpha(colors.border, 0.4),
      paddingVertical: ui.spacing.xs,
      paddingHorizontal: 0,
    },
    questDivider: {
      height: 1,
      backgroundColor: withAlpha(colors.border, 0.42),
      marginVertical: 1,
    },
    questHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: ui.spacing.xs,
      paddingHorizontal: 0,
      paddingVertical: ui.spacing.xs,
    },
    questHeaderPressed: {
      opacity: 0.82,
    },
    questMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: ui.spacing.xs,
      marginTop: ui.spacing.xxs,
    },
    questMetaDifficulty: {
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 0.6,
      textTransform: "uppercase",
      opacity: 0.82,
    },
    questMetaCategory: {
      fontSize: 11,
      fontWeight: "600",
      lineHeight: 15,
      opacity: 0.76,
    },
    questStatusStack: {
      alignItems: "flex-end",
      gap: 6,
    },
    statusPill: {
      paddingVertical: 0,
      paddingHorizontal: 0,
      borderRadius: 999,
      fontSize: 9,
      fontWeight: "900",
      letterSpacing: 0.3,
    },
    statusPillIcon: {
      paddingVertical: 2,
      paddingHorizontal: 2,
      borderRadius: ui.radius.sm,
      alignItems: "center",
      justifyContent: "center",
    },
    questActionsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: ui.spacing.xs,
      alignItems: "center",
      paddingTop: ui.spacing.xs,
    },
    questActionBtn: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 10,
      borderWidth: 1.5,
    },
    questActionText: { fontWeight: "900", fontSize: 12 },
    questDone: {
      opacity: 0.82,
      borderColor: withAlpha(colors.accentPrimary, 0.38),
    },
    questDoneBar: {
      height: 1,
      borderRadius: 999,
      backgroundColor: `${colors.accentSecondary}55`,
      marginBottom: ui.spacing.xs,
    },
    questTitle: { color: colors.textPrimary, fontSize: 15, fontWeight: "800" },
    questTitleDone: { textDecorationLine: "line-through", opacity: 0.6 },
    questMeta: { color: colors.textSecondary, marginTop: 6, fontSize: 12 },

    rightStack: { gap: 9, alignItems: "flex-end" },

    completeBtn: {
      backgroundColor: colors.accentPrimary,
      paddingVertical: 9,
      paddingHorizontal: 12,
      borderRadius: 9,
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
    },
    completeText: { color: colors.textPrimary, fontWeight: "900", fontSize: 11 },

    doneBadge: {
      backgroundColor: `${colors.accentSecondary}1A`,
      borderWidth: 1.5,
      borderColor: colors.accentSecondary,
      paddingVertical: 9,
      paddingHorizontal: 11,
      borderRadius: 9,
    },
    doneText: { color: colors.accentSecondary, fontWeight: "900", fontSize: 11 },

    editBtn: {
      backgroundColor: colors.bg,
      borderWidth: 1.5,
      borderColor: colors.border,
      paddingVertical: 7,
      paddingHorizontal: 11,
      borderRadius: 9,
    },
    editText: { color: colors.textPrimary, fontWeight: "900", fontSize: 11 },

    pinBtn: {
      backgroundColor: colors.bg,
      borderWidth: 1.5,
      borderColor: colors.border,
      paddingVertical: 7,
      paddingHorizontal: 11,
      borderRadius: 9,
    },
    pinText: { color: colors.textSecondary, fontWeight: "900", fontSize: 11 },

    deleteBtn: {
      backgroundColor: colors.bg,
      borderWidth: 1.5,
      borderColor: colors.accentPrimary,
      paddingVertical: 7,
      paddingHorizontal: 11,
      borderRadius: 9,
    },
    deleteText: { color: colors.accentPrimary, fontWeight: "900", fontSize: 11 },

    btnPressed: {
      opacity: 0.7,
      transform: [{ scale: 0.95 }],
    },

    grid: { gap: 12 },
    card: {
      ...cardSurface,
      padding: ui.spacing.card,
      borderRadius: ui.radius.md,
    },
    cardSecondary: {
      ...secondaryCardSurface,
      padding: ui.spacing.md,
    },
    focusList: { marginTop: ui.spacing.sm },
    focusRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: ui.spacing.sm,
      paddingHorizontal: 0,
      backgroundColor: "transparent",
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "transparent",
    },
    focusLabel: {
      ...ui.typography.body,
      color: colors.textPrimary,
      fontWeight: "700",
      opacity: 0.9,
    },
    focusMeta: {
      ...ui.typography.caption,
      marginTop: 0,
      color: withAlpha(colors.textSecondary, 0.88),
      fontWeight: "700",
      textAlign: "right",
    },
    focusDivider: {
      height: 1,
      backgroundColor: withAlpha(colors.border, 0.28),
    },
    cardTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "baseline",
      marginBottom: 9,
    },
    cardTitle: { ...ui.typography.heading, color: colors.textPrimary, fontSize: 18 },
    drSystemSubhead: {
      color: colors.textSecondary,
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 0.3,
      textTransform: "uppercase",
      marginTop: 14,
      marginBottom: 8,
    },
    drSystemTopRow: {
      backgroundColor: withAlpha(colors.accentPrimary, 0.08),
      borderWidth: ui.border.width,
      borderColor: withAlpha(colors.accentPrimary, 0.25),
      borderRadius: ui.radius.md,
      paddingVertical: ui.spacing.xs,
      paddingHorizontal: ui.spacing.sm,
      marginBottom: ui.spacing.sm,
    },
    drSystemTopText: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: "700",
      lineHeight: 18,
    },
    drSystemRow: {
      backgroundColor: colors.surface2,
      borderWidth: ui.border.width,
      borderColor: withAlpha(colors.border, 0.42),
      borderRadius: ui.radius.md,
      paddingVertical: ui.spacing.xs,
      paddingHorizontal: ui.spacing.sm,
      marginTop: 6,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    drSystemRowActive: {
      borderColor: colors.accentPrimary,
      backgroundColor: `${colors.accentPrimary}1A`,
    },
    statsSectionFlat: {
      marginBottom: ui.spacing.md,
    },
    analyticsRow: {
      flexDirection: "row",
      gap: ui.spacing.xs,
      marginBottom: ui.spacing.md,
    },
    analyticsTile: {
      flex: 1,
      borderWidth: 1,
      borderColor: withAlpha(colors.border, 0.38),
      borderRadius: ui.radius.sm,
      paddingVertical: ui.spacing.xs,
      paddingHorizontal: ui.spacing.xs,
      backgroundColor: withAlpha(colors.surface2, 0.28),
    },
    analyticsLabel: {
      ...ui.typography.caption,
      color: colors.textSecondary,
      fontSize: 9,
      letterSpacing: 0.65,
    },
    analyticsValue: {
      ...ui.typography.mono,
      color: colors.textPrimary,
      fontSize: 15,
      marginTop: 2,
    },
    statsSectionDivider: {
      height: 1,
      backgroundColor: withAlpha(colors.border, 0.32),
      marginTop: ui.spacing.sm,
      marginBottom: ui.spacing.md,
    },
    tableHeaderRow: {
      flexDirection: "row",
      paddingVertical: ui.spacing.xs,
      borderBottomWidth: 1,
      borderBottomColor: withAlpha(colors.border, 0.48),
      marginBottom: ui.spacing.xxs,
    },
    tableHeaderText: {
      ...ui.typography.caption,
      color: withAlpha(colors.textSecondary, 0.9),
      fontSize: 10,
      letterSpacing: 0.7,
    },
    tableRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: ui.spacing.xs,
      borderBottomWidth: 1,
      borderBottomColor: withAlpha(colors.border, 0.28),
    },
    tableCell: {
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: "700",
    },
    drRankRow: {
      backgroundColor: colors.surface,
      borderWidth: 0,
      borderRadius: ui.radius.md,
      paddingVertical: ui.spacing.sm,
      paddingHorizontal: ui.spacing.sm,
      marginTop: ui.spacing.sm,
      minHeight: 52,
      flexDirection: "row",
      alignItems: "center",
      shadowColor: colors.text,
      shadowOffset: ui.shadow.soft.shadowOffset,
      shadowOpacity: 0.07,
      shadowRadius: ui.shadow.soft.shadowRadius,
      elevation: ui.shadow.soft.elevation,
    },
    drRankRowActive: {
      backgroundColor: withAlpha(colors.accentPrimary, 0.1),
    },
    drRankAccentBar: {
      width: 3,
      alignSelf: "stretch",
      borderRadius: 999,
      marginRight: ui.spacing.sm,
      backgroundColor: colors.accentPrimary,
    },
    drRankRowContent: {
      flex: 1,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    drSystemRankName: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: "700",
    },
    drSystemRankRange: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: "800",
    },
    drSystemRuleLabel: {
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: "700",
    },
    drSystemRuleDelta: {
      fontSize: 12,
      fontWeight: "900",
    },
    level: { fontSize: 14, fontWeight: "700", color: colors.accentPrimary, letterSpacing: 0.2 },
    xpText: { color: colors.textSecondary, marginBottom: 9, fontSize: 12, fontWeight: "500" },
    barTrack: {
      height: 11,
      borderRadius: 5.5,
      backgroundColor: colors.bg,
      overflow: "hidden",
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    barFill: { height: "100%", backgroundColor: colors.accentPrimary, borderRadius: 5.5 },

    difficultyEasy: {
      backgroundColor: `${colors.accentTertiary}1A`,
      borderWidth: 2,
      borderColor: colors.accentTertiary,
      paddingVertical: 5,
      paddingHorizontal: 9,
      borderRadius: 7,
      shadowColor: colors.accentTertiary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
    },
    difficultyMedium: {
      backgroundColor: `${colors.accentSecondary}1A`,
      borderWidth: 2,
      borderColor: colors.accentSecondary,
      paddingVertical: 5,
      paddingHorizontal: 9,
      borderRadius: 7,
      shadowColor: colors.accentSecondary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
    },
    difficultyHard: {
      backgroundColor: `${colors.accentPrimary}1A`,
      borderWidth: 2,
      borderColor: colors.accentPrimary,
      paddingVertical: 5,
      paddingHorizontal: 9,
      borderRadius: 7,
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
    },
    difficultyText: { fontWeight: "900", fontSize: 10, color: colors.textPrimary, letterSpacing: 0.2 },

    // Achievements
    achievementSection: { marginBottom: 28, marginTop: 28 },
    achievementHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    achievementProgress: {
      backgroundColor: colors.surface,
      borderRadius: ui.radius.md,
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderWidth: ui.border.widthStrong,
      borderColor: withAlpha(colors.border, ui.border.opacityCard),
    },
    achievementProgressText: { color: colors.accentPrimary, fontWeight: "800", fontSize: 13 },
    achievementGrid: { gap: 12 },
    achievementBadge: {
      ...cardSurface,
      borderRadius: ui.radius.lg,
      padding: ui.spacing.md,
      alignItems: "center",
      gap: 8,
    },
    achievementUnlocked: {
      backgroundColor: `${colors.accentSecondary}1A`,
      borderColor: colors.accentSecondary,
      shadowColor: colors.accentSecondary,
      shadowRadius: 6,
    },
    achievementLocked: {
      opacity: 0.4,
      backgroundColor: colors.bg,
      borderColor: colors.border,
    },
    achievementIcon: { fontSize: 32 },
    achievementName: { color: colors.textPrimary, fontWeight: "900", fontSize: 13, textAlign: "center" },
    achievementDesc: { color: colors.textSecondary, fontWeight: "600", fontSize: 12, textAlign: "center" },
    achievementDate: { color: colors.accentSecondary, fontWeight: "800", fontSize: 11, marginTop: 4 },

    hint: { marginTop: 24, color: colors.textSecondary, lineHeight: 20, fontSize: 13 },
    homeHintCard: {
      marginTop: ui.spacing.sm,
      paddingVertical: ui.spacing.xs,
      paddingHorizontal: 0,
      borderTopWidth: 1,
      borderTopColor: withAlpha(colors.border, 0.28),
    },
    homeHintText: {
      color: withAlpha(colors.textSecondary, 0.84),
      lineHeight: ui.typography.body.lineHeight,
      fontSize: ui.typography.body.fontSize,
      fontWeight: "600",
      opacity: 0.9,
    },
  });
};
