import { StyleSheet } from "react-native";
import { createCardSurface, createTileSurface, ui, withAlpha } from "./_utils/designSystem";
import type { ThemeColors } from "./_utils/themeContext";

export const createStyles = (colors: ThemeColors) => {
  const cardSurface = createCardSurface(colors, {
    padding: ui.spacing.card,
    radius: ui.radius.card,
  });

  const secondaryCardSurface = createCardSurface(colors, {
    padding: ui.spacing.card,
    radius: ui.radius.card,
    glowOpacity: 0.04,
    borderOpacity: ui.border.opacitySecondary,
    backgroundColor: colors.surface2,
  });
  const tileSurface = createTileSurface(colors);
  const compactTileSurface = createTileSurface(colors, {
    padding: ui.spacing.xs,
    radius: ui.radius.md,
    borderOpacity: 0.2,
    backgroundOpacity: 0.2,
  });

  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.bg },
    screen: { flex: 1, backgroundColor: colors.bg },
    bgArt: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    sectionBand: {
      paddingHorizontal: 0,
      paddingVertical: ui.spacing.md,
    },
    sectionBandTight: {
      paddingBottom: ui.spacing.sm,
    },
    container: {
      paddingHorizontal: ui.spacing.screen,
      paddingTop: ui.spacing.screen,
      paddingBottom: ui.spacing.xl * 3,
    },

    title: {
      ...ui.typography.title,
      color: colors.textPrimary,
      marginBottom: 0,
      fontSize: 24,
      lineHeight: 28,
      fontWeight: "900",
      letterSpacing: 1,
    },
    homeSubtitle: {
      color: colors.textTertiary,
      fontSize: 12,
      fontWeight: "600",
      marginTop: 4,
      marginBottom: 0,
      lineHeight: 15,
      letterSpacing: 0.55,
      textTransform: "uppercase",
    },
    homeTopBar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: ui.spacing.lg,
      paddingBottom: ui.spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: withAlpha(colors.divider, 0.8),
    },
    homeTitleWrap: {
      gap: 3,
    },
    brandTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    homeMetaText: {
      ...ui.typography.caption,
      color: colors.textPrimary,
      fontSize: 11,
      fontWeight: "900",
      letterSpacing: 0.6,
      textTransform: "uppercase",
    },
    homeMetaPill: {
      borderWidth: 1,
      borderColor: withAlpha(colors.accentPrimary, 0.28),
      backgroundColor: withAlpha(colors.accentPrimary, 0.08),
      borderRadius: 999,
      paddingHorizontal: ui.spacing.sm,
      paddingVertical: 6,
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 1,
    },
    dayScoreCard: {
      ...secondaryCardSurface,
      position: "relative",
      overflow: "hidden",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: ui.spacing.lg + ui.spacing.xs,
      paddingVertical: ui.spacing.md + ui.spacing.xs,
      borderColor: withAlpha(colors.accentPrimary, 0.16),
      borderWidth: 0.6,
      backgroundColor: withAlpha(colors.surface2, 0.96),
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.04,
      shadowRadius: 8,
      elevation: 1,
    },
    dayScoreWatermarkWrap: {
      position: "absolute",
      right: -46,
      top: -44,
      opacity: 0.22,
    },
    dayScoreWatermarkSoftWrap: {
      position: "absolute",
      right: -58,
      top: -56,
      opacity: 0.15,
    },
    missionHero: {
      position: "relative",
      overflow: "visible",
      borderWidth: 0,
      borderColor: "transparent",
      backgroundColor: "transparent",
      borderRadius: 0,
      padding: 0,
      gap: ui.spacing.sm,
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    missionHeroHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: ui.spacing.sm,
    },
    missionEyebrow: {
      ...ui.typography.caption,
      color: withAlpha(colors.textSecondary, 0.82),
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 0.75,
      textTransform: "uppercase",
    },
    missionTitle: {
      color: colors.textPrimary,
      fontSize: 27,
      lineHeight: 31,
      fontWeight: "900",
      marginTop: 2,
    },
    missionCountdownPill: {
      borderWidth: 1,
      borderColor: withAlpha(colors.accentPrimary, 0.28),
      backgroundColor: withAlpha(colors.accentPrimary, 0.08),
      borderRadius: 999,
      paddingHorizontal: ui.spacing.sm,
      paddingVertical: 7,
      alignItems: "flex-end",
      minWidth: 96,
    },
    missionCountdownLabel: {
      ...ui.typography.caption,
      color: withAlpha(colors.textSecondary, 0.82),
      fontSize: 9,
      lineHeight: 12,
      fontWeight: "800",
      letterSpacing: 0.7,
      textTransform: "uppercase",
    },
    missionCountdownValue: {
      color: colors.textPrimary,
      fontSize: 17,
      lineHeight: 21,
      fontWeight: "900",
      marginTop: 1,
    },
    missionHeroBody: {
      flexDirection: "row",
      alignItems: "center",
      gap: ui.spacing.sm,
    },
    missionRingSlot: {
      flexShrink: 0,
      transform: [{ scale: 0.86 }],
      marginLeft: -13,
      marginRight: -16,
      marginVertical: -13,
    },
    missionStatsPanel: {
      ...tileSurface,
      flex: 1,
      paddingHorizontal: ui.spacing.sm,
      paddingVertical: ui.spacing.sm,
      gap: 7,
      minWidth: 0,
    },
    missionStatRow: {
      flexDirection: "row",
      alignItems: "flex-end",
      justifyContent: "space-between",
      gap: ui.spacing.xs,
    },
    missionStatLabel: {
      ...ui.typography.caption,
      color: withAlpha(colors.textSecondary, 0.82),
      fontSize: 10,
      lineHeight: 13,
      fontWeight: "800",
      letterSpacing: 0.7,
      textTransform: "uppercase",
      paddingBottom: 7,
    },
    missionDrValue: {
      ...ui.typography.drHero,
      color: colors.textPrimary,
      fontSize: 48,
      lineHeight: 52,
      fontWeight: "900",
      letterSpacing: -0.4,
    },
    missionScorePanel: {
      ...cardSurface,
      borderColor: withAlpha(colors.border, 0.24),
      backgroundColor: withAlpha(colors.surface2, 0.72),
      borderRadius: ui.radius.card,
      paddingHorizontal: ui.spacing.md,
      paddingVertical: ui.spacing.md,
      gap: 10,
    },
    missionScoreTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-end",
      gap: ui.spacing.sm,
    },
    missionScoreLabel: {
      ...ui.typography.caption,
      color: withAlpha(colors.textSecondary, 0.82),
      fontSize: 10,
      lineHeight: 13,
      fontWeight: "800",
      letterSpacing: 0.75,
      textTransform: "uppercase",
    },
    missionScoreValue: {
      color: colors.textPrimary,
      fontSize: 48,
      lineHeight: 52,
      fontWeight: "900",
      marginTop: 2,
    },
    missionScoreMeta: {
      color: withAlpha(colors.textSecondary, 0.86),
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "800",
      letterSpacing: 0.2,
      paddingBottom: 6,
      textTransform: "uppercase",
    },
    missionScoreTrack: {
      height: 12,
      borderRadius: 999,
      backgroundColor: withAlpha(colors.bg, 0.78),
      overflow: "hidden",
      borderWidth: 1,
      borderColor: withAlpha(colors.border, 0.36),
    },
    missionScoreFill: {
      height: "100%",
      borderRadius: 999,
    },
    missionMetricGrid: {
      flexDirection: "row",
      gap: ui.spacing.sm,
    },
    missionMetricTile: {
      ...compactTileSurface,
      flex: 1,
      paddingHorizontal: ui.spacing.sm,
      paddingVertical: ui.spacing.sm,
      gap: 7,
      minWidth: 0,
    },
    missionMetricLabel: {
      ...ui.typography.caption,
      color: withAlpha(colors.textSecondary, 0.82),
      fontSize: 10,
      lineHeight: 13,
      fontWeight: "800",
      letterSpacing: 0.65,
      textTransform: "uppercase",
    },
    missionMetricValueRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: ui.spacing.xs,
    },
    missionMetricValue: {
      color: colors.textPrimary,
      fontSize: 34,
      lineHeight: 38,
      fontWeight: "900",
      minWidth: 32,
    },
    missionMetricValueSmall: {
      color: colors.textPrimary,
      fontSize: 24,
      lineHeight: 28,
      fontWeight: "900",
    },
    statusHeader: {
      backgroundColor: withAlpha(colors.surface2, 0.36),
      borderWidth: 0,
      borderRadius: ui.radius.xl,
      paddingHorizontal: ui.spacing.lg,
      paddingTop: ui.spacing.sm,
      paddingBottom: ui.spacing.sm + ui.spacing.xxs,
      gap: ui.spacing.xs,
    },
    statusHeaderTop: {
      flexDirection: "column",
      alignItems: "center",
      gap: ui.spacing.xs,
      paddingBottom: ui.spacing.xs,
    },
    statusHeaderMain: {
      width: "100%",
      gap: 4,
      justifyContent: "center",
      alignItems: "center",
    },
    rankBadgeRail: {
      marginBottom: ui.spacing.xs,
      alignItems: "center",
      justifyContent: "center",
    },
    statusLabel: {
      ...ui.typography.caption,
      color: "#8B98A5",
      fontSize: 12,
      letterSpacing: 0.8,
    },
    statusDrValue: {
      ...ui.typography.drHero,
      color: "#E6EDF3",
      fontSize: 80,
      lineHeight: 80,
      fontWeight: "900",
      marginTop: 0,
      textAlign: "center",
      letterSpacing: -1,
    },
    statusRankBadge: {
      marginTop: 3,
      borderWidth: 1,
      borderColor: withAlpha(colors.accentPrimary, 0.52),
      backgroundColor: withAlpha(colors.accentPrimary, 0.14),
      borderRadius: 999,
      paddingHorizontal: ui.spacing.xs,
      paddingVertical: 3,
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 2,
      flex: 1,
      alignItems: "center",
      minWidth: 0,
    },
    statusRankBadgeText: {
      fontSize: 11,
      fontWeight: "900",
      letterSpacing: 0.2,
      color: "#E6EDF3",
      textTransform: "uppercase",
      textAlign: "center",
    },
    statusRankName: {
      marginTop: 3,
      fontSize: 11,
      fontWeight: "900",
      letterSpacing: 0.6,
      color: "#E6EDF3",
      textTransform: "uppercase",
    },
    statusRankNext: {
      marginTop: 4,
      ...ui.typography.caption,
      color: "#8B98A5",
      fontSize: 11,
      letterSpacing: 0.45,
      textTransform: "uppercase",
    },
    rankProgressBlock: {
      width: "100%",
      marginTop: ui.spacing.xs,
      gap: 6,
    },
    rankProgressCurrent: {
      ...ui.typography.caption,
      color: "#E6EDF3",
      fontSize: 12,
      fontWeight: "800",
      letterSpacing: 0.45,
      textTransform: "uppercase",
      textAlign: "left",
    },
    rankProgressTarget: {
      ...ui.typography.caption,
      color: "#8B98A5",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.3,
      textAlign: "left",
    },
    rankProgressTrack: {
      height: 10,
      width: "100%",
      borderRadius: 999,
      backgroundColor: withAlpha(colors.bg, 0.9),
      borderWidth: 1,
      borderColor: withAlpha(colors.cardBorder, 0.5),
      overflow: "hidden",
    },
    rankProgressFill: {
      height: "100%",
      borderRadius: 999,
      opacity: 0.9,
    },
    rankProgressMeta: {
      ...ui.typography.caption,
      color: "#E6EDF3",
      fontSize: 11,
      fontWeight: "600",
      letterSpacing: 0.2,
      textAlign: "left",
    },
    statusProgressBlock: {
      paddingTop: ui.spacing.xs,
      gap: 6,
    },
    statusProgressRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    statusProgressLabel: {
      ...ui.typography.caption,
      color: "#8B98A5",
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 0.3,
    },
    statusProgressValue: {
      ...ui.typography.caption,
      color: "#E6EDF3",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.25,
    },
    statusProgressTrack: {
      height: 9,
      width: "100%",
      borderRadius: 999,
      backgroundColor: withAlpha(colors.bg, 0.9),
      borderWidth: 1,
      borderColor: withAlpha(colors.cardBorder, 0.5),
      overflow: "hidden",
    },
    statusProgressFill: {
      height: "100%",
      borderRadius: 999,
      opacity: 0.86,
    },
    statusStatsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      rowGap: ui.spacing.xs,
      paddingTop: ui.spacing.sm,
    },
    statusStatCell: {
      width: "49%",
      borderWidth: 1,
      borderColor: withAlpha(colors.cardBorder, 0.42),
      borderRadius: ui.radius.md,
      backgroundColor: withAlpha(colors.surface, 0.16),
      paddingVertical: 5,
      paddingHorizontal: ui.spacing.xs,
      gap: 1,
      alignItems: "flex-start",
    },
    statusStatLabel: {
      ...ui.typography.caption,
      color: "#8B98A5",
      fontSize: 9,
      letterSpacing: 0.5,
      textTransform: "uppercase",
    },
    statusStatValue: {
      ...ui.typography.mono,
      fontSize: 22,
      lineHeight: 26,
      fontWeight: "800",
      color: "#E6EDF3",
      letterSpacing: 0,
    },
    statusStatValueStrong: {
      fontSize: 23,
      lineHeight: 27,
      fontWeight: "900",
    },
    devActionChip: {
      marginTop: ui.spacing.xs,
      alignSelf: "flex-start",
      borderWidth: 1,
      borderColor: colors.negative,
      borderRadius: ui.radius.sm,
      paddingVertical: ui.spacing.xxs,
      paddingHorizontal: ui.spacing.sm,
    },
    devActionRow: {
      flexDirection: "row",
      gap: ui.spacing.xs,
      marginTop: ui.spacing.xs,
    },
    devActionText: {
      ...ui.typography.caption,
      color: colors.negative,
      fontSize: 11,
      letterSpacing: 0.6,
    },

    topRow: { flexDirection: "row", gap: 10, marginBottom: ui.spacing.md, flexWrap: "wrap" },
    pill: {
      backgroundColor: colors.surface,
      borderRadius: ui.radius.card,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderWidth: ui.border.width,
      borderColor: withAlpha(colors.border, ui.border.opacityCard),
      flex: 1,
      minWidth: 110,
      shadowColor: colors.text,
      shadowOffset: ui.shadow.soft.shadowOffset,
      shadowOpacity: ui.shadow.soft.shadowOpacity,
      shadowRadius: ui.shadow.soft.shadowRadius,
      elevation: ui.shadow.soft.elevation,
    },
    todayPill: {
      backgroundColor: colors.bg,
      position: "relative",
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 10,
    },
    pillLabel: { color: colors.textSecondary, fontSize: 11, fontWeight: "600", letterSpacing: 0.3, textTransform: "uppercase" },
    pillValue: { color: colors.accentPrimary, fontSize: 15, fontWeight: "900", marginTop: 3, letterSpacing: 0.3 },
    drPrimaryPill: {
      width: "100%",
      flexBasis: "100%",
      minWidth: "100%",
      paddingVertical: ui.spacing.xl,
      paddingHorizontal: ui.spacing.md,
      borderWidth: ui.border.width,
      alignItems: "center",
      shadowColor: colors.text,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.05,
      shadowRadius: 6,
      elevation: 1,
    },
    drPrimaryValue: {
      ...ui.typography.drHero,
      fontSize: 60,
      lineHeight: 64,
      marginTop: ui.spacing.sm,
      marginBottom: ui.spacing.xs,
      textAlign: "center",
      textShadowColor: withAlpha(colors.accentPrimary, 0.28),
      textShadowOffset: { width: 0, height: 0 },
      textShadowRadius: 9,
    },
    drRankText: {
      marginTop: ui.spacing.xs,
      fontSize: 14,
      fontWeight: "800",
      letterSpacing: 0.2,
      textAlign: "center",
    },
    drSupportText: {
      textAlign: "center",
      marginTop: ui.spacing.xs,
      fontSize: ui.typography.body.fontSize,
      lineHeight: ui.typography.body.lineHeight,
      opacity: 0.86,
    },
    drProgressBlock: {
      width: "100%",
      marginTop: 12,
      alignItems: "center",
    },
    drProgressTrack: {
      width: "100%",
      height: 8,
      borderRadius: 999,
      borderWidth: 1,
      overflow: "hidden",
    },
    drProgressFill: {
      height: "100%",
      borderRadius: 999,
    },
    drProgressText: {
      marginTop: 6,
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    drLabelText: {
      fontSize: 13,
      fontWeight: "800",
      letterSpacing: 0.35,
      textTransform: "uppercase",
    },
    secondaryPillLabel: {
      fontSize: 9,
      opacity: 0.75,
    },
    secondaryPillValue: {
      fontSize: 13,
      marginTop: 2,
      opacity: 0.85,
    },
    todayLabelRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
    todayAccentDot: { width: 6, height: 6, borderRadius: 999 },
    todayContent: { zIndex: 1, alignItems: "center" },
    todayRingWrap: { position: "absolute", zIndex: 0 },
    todayXPRow: {
      alignSelf: "center",
      backgroundColor: `${colors.accentPrimary}1A`,
      borderRadius: 9,
      paddingVertical: 4,
      paddingHorizontal: 8,
      marginTop: 6,
    },
    todayValue: {
      fontSize: 14,
      textShadowColor: colors.accentPrimary,
      textShadowOffset: { width: 0, height: 0 },
      textShadowRadius: 6,
    },
    todaySummaryCard: {
      marginTop: ui.spacing.md,
      borderRadius: ui.radius.card,
      borderWidth: 0,
      paddingVertical: ui.spacing.md,
      paddingHorizontal: ui.spacing.md,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    todaySummaryLabel: {
      fontSize: 12,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.3,
    },
    todaySummaryValue: {
      fontSize: 13,
      fontWeight: "800",
    },

    row: { flexDirection: "row", gap: 10, marginBottom: ui.spacing.md, flexWrap: "wrap" },
    homeActionRow: { flexDirection: "row", gap: ui.spacing.sm, marginTop: ui.spacing.md, marginBottom: 0 },
    btn: {
      backgroundColor: colors.surface,
      paddingVertical: 11,
      paddingHorizontal: 14,
      borderRadius: ui.radius.button,
      borderWidth: 1,
      borderColor: withAlpha(colors.border, 0.3),
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
    },
    btnDanger: {
      backgroundColor: colors.bg,
      paddingVertical: 11,
      paddingHorizontal: 14,
      borderRadius: ui.radius.button,
      borderWidth: 1,
      borderColor: withAlpha(colors.accentPrimary, 0.35),
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
    },
    btnText: { color: colors.textPrimary, fontWeight: "800", fontSize: 13 },
    homeActionBtn: {
      flex: 1,
      backgroundColor: colors.surface,
      borderColor: withAlpha(colors.border, 0.3),
      borderWidth: 1,
      borderRadius: ui.radius.lg,
      paddingVertical: 12,
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
    },
    homeActionBtnDanger: {
      flex: 1,
      backgroundColor: colors.bg,
      borderColor: withAlpha(colors.accentPrimary, 0.35),
      borderWidth: 1,
      borderRadius: ui.radius.lg,
      paddingVertical: 12,
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
    },
    homeActionText: { color: colors.textPrimary, fontWeight: "900", fontSize: 12, letterSpacing: 0.2 },

    sectionRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: ui.spacing.xs,
      marginTop: 0,
    },
    section: { ...ui.typography.heading, color: colors.textPrimary },
    sectionSecondary: {
      ...ui.typography.caption,
      color: withAlpha(colors.textSecondary, 0.78),
      fontSize: 12,
      lineHeight: 15,
      textTransform: "uppercase",
      letterSpacing: 0.6,
      marginBottom: ui.spacing.sm,
    },
    sectionSubtext: {
      color: withAlpha(colors.textSecondary, 0.8),
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 0,
      marginTop: 0,
    },
    link: { color: colors.accentPrimary, fontWeight: "900", fontSize: 13, letterSpacing: 0.3 },
    dailySection: {
      marginTop: ui.spacing.lg,
    },
    dailyHeaderCard: {
      borderWidth: 0,
      backgroundColor: "transparent",
      borderRadius: 0,
      paddingHorizontal: 0,
      paddingTop: 0,
      paddingBottom: ui.spacing.xxs,
      marginBottom: ui.spacing.xs,
    },
    contractPanel: {
      borderWidth: 0,
      borderTopWidth: 1,
      borderTopColor: withAlpha(colors.border, 0.24),
      backgroundColor: "transparent",
      borderRadius: 0,
      paddingHorizontal: 0,
      paddingTop: ui.spacing.sm,
      paddingBottom: 0,
      marginBottom: 0,
      gap: 9,
    },
    contractHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: ui.spacing.sm,
    },
    contractEyebrow: {
      ...ui.typography.caption,
      color: colors.textSecondary,
      fontSize: 10,
      letterSpacing: 0.75,
      textTransform: "uppercase",
    },
    contractTitle: {
      color: colors.textPrimary,
      fontSize: 18,
      lineHeight: 22,
      fontWeight: "900",
      marginTop: 2,
    },
    contractCounterPill: {
      borderWidth: 1,
      borderColor: withAlpha(colors.accentPrimary, 0.48),
      backgroundColor: withAlpha(colors.accentPrimary, 0.16),
      borderRadius: 999,
      paddingHorizontal: ui.spacing.sm,
      paddingVertical: 5,
    },
    contractCounterText: {
      color: colors.textPrimary,
      fontSize: 11,
      fontWeight: "900",
      letterSpacing: 0.35,
    },
    contractProgressTrack: {
      height: 9,
      borderRadius: 999,
      backgroundColor: withAlpha(colors.bg, 0.8),
      overflow: "hidden",
      borderWidth: 1,
      borderColor: withAlpha(colors.border, 0.36),
    },
    contractProgressFill: {
      height: "100%",
      borderRadius: 999,
    },
    contractStatusText: {
      color: withAlpha(colors.textSecondary, 0.86),
      fontSize: 12,
      lineHeight: 17,
      fontWeight: "600",
    },
    morningPlanPanel: {
      borderTopWidth: 1,
      borderTopColor: withAlpha(colors.border, 0.24),
      paddingTop: ui.spacing.sm,
      gap: ui.spacing.xs,
    },
    morningPlanHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: ui.spacing.sm,
    },
    morningPlanTitle: {
      color: colors.textPrimary,
      fontSize: 18,
      lineHeight: 22,
      fontWeight: "900",
      marginTop: 2,
    },
    morningPlanDeltaPill: {
      borderWidth: 1,
      borderColor: withAlpha(colors.accentPrimary, 0.28),
      backgroundColor: withAlpha(colors.accentPrimary, 0.08),
      borderRadius: 999,
      paddingHorizontal: ui.spacing.sm,
      paddingVertical: 6,
      alignItems: "flex-end",
      minWidth: 62,
    },
    morningPlanDeltaLabel: {
      color: withAlpha(colors.textSecondary, 0.84),
      fontSize: 9,
      lineHeight: 11,
      fontWeight: "800",
      letterSpacing: 0.5,
      textTransform: "uppercase",
    },
    morningPlanDeltaValue: {
      color: colors.textPrimary,
      fontSize: 16,
      lineHeight: 19,
      fontWeight: "900",
    },
    morningPlanBody: {
      color: withAlpha(colors.textSecondary, 0.9),
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "600",
    },
    morningPlanMetricRow: {
      flexDirection: "row",
      gap: ui.spacing.xs,
      marginTop: 2,
    },
    morningPlanMetric: {
      ...compactTileSurface,
      flex: 1,
      paddingHorizontal: ui.spacing.xs,
      paddingVertical: 7,
      minWidth: 0,
    },
    morningPlanMetricValue: {
      color: colors.textPrimary,
      fontSize: 15,
      lineHeight: 18,
      fontWeight: "900",
    },
    morningPlanMetricLabel: {
      color: withAlpha(colors.textSecondary, 0.78),
      fontSize: 9,
      lineHeight: 12,
      fontWeight: "800",
      letterSpacing: 0.35,
      textTransform: "uppercase",
      marginTop: 1,
    },
    nextMoveCard: {
      ...cardSurface,
      borderColor: withAlpha(colors.accentPrimary, 0.22),
      backgroundColor: withAlpha(colors.surface2, 0.82),
      borderRadius: ui.radius.card,
      paddingHorizontal: ui.spacing.md,
      paddingVertical: ui.spacing.md,
      marginBottom: ui.spacing.sm,
      gap: 8,
    },
    nextMoveTopRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: ui.spacing.sm,
    },
    nextMoveEyebrow: {
      ...ui.typography.caption,
      color: colors.accentPrimary,
      fontSize: 10,
      lineHeight: 13,
      fontWeight: "900",
      letterSpacing: 0.75,
      textTransform: "uppercase",
    },
    nextMoveTitle: {
      color: colors.textPrimary,
      fontSize: 21,
      lineHeight: 25,
      fontWeight: "900",
      marginTop: 2,
      maxWidth: 200,
    },
    nextMoveButton: {
      borderRadius: ui.radius.button,
      backgroundColor: colors.accentPrimary,
      paddingHorizontal: ui.spacing.md,
      paddingVertical: 11,
      minWidth: 96,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.18,
      shadowRadius: 8,
      elevation: 2,
    },
    nextMoveButtonText: {
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: "900",
      letterSpacing: 0.25,
    },
    nextMoveCompletePill: {
      borderWidth: 1,
      borderColor: withAlpha(colors.accentPrimary, 0.38),
      backgroundColor: withAlpha(colors.accentPrimary, 0.12),
      borderRadius: 999,
      paddingHorizontal: ui.spacing.sm,
      paddingVertical: 7,
      alignItems: "center",
      justifyContent: "center",
    },
    nextMoveCompleteText: {
      color: colors.accentPrimary,
      fontSize: 11,
      fontWeight: "900",
      letterSpacing: 0.45,
      textTransform: "uppercase",
    },
    nextMoveBadge: {
      alignSelf: "flex-start",
      borderWidth: 1,
      borderColor: withAlpha(colors.accentPrimary, 0.34),
      backgroundColor: withAlpha(colors.accentPrimary, 0.1),
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 4,
    },
    nextMoveBadgeText: {
      color: colors.accentPrimary,
      fontSize: 10,
      lineHeight: 13,
      fontWeight: "900",
      letterSpacing: 0.55,
      textTransform: "uppercase",
    },
    nextMoveMeta: {
      color: withAlpha(colors.textSecondary, 0.84),
      fontSize: 11,
      lineHeight: 15,
      fontWeight: "800",
      letterSpacing: 0.35,
      textTransform: "uppercase",
    },
    nextMoveReason: {
      color: withAlpha(colors.textSecondary, 0.86),
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "600",
    },
    templatePanel: {
      borderWidth: 0,
      borderTopWidth: 1,
      borderTopColor: withAlpha(colors.border, 0.24),
      paddingTop: ui.spacing.sm,
      marginBottom: ui.spacing.md,
    },
    templateHint: {
      color: withAlpha(colors.textSecondary, 0.72),
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 0.35,
      textTransform: "uppercase",
    },
    templateRail: {
      gap: ui.spacing.xs,
      paddingRight: ui.spacing.screen,
      paddingBottom: 2,
    },
    templateChip: {
      ...compactTileSurface,
      width: 142,
      minHeight: 76,
      paddingHorizontal: ui.spacing.sm,
      paddingVertical: ui.spacing.sm,
      justifyContent: "space-between",
    },
    templateTitle: {
      color: colors.textPrimary,
      fontSize: 13,
      lineHeight: 17,
      fontWeight: "800",
    },
    templateMeta: {
      color: withAlpha(colors.textSecondary, 0.78),
      fontSize: 10,
      lineHeight: 13,
      fontWeight: "800",
      letterSpacing: 0.25,
      textTransform: "uppercase",
      marginTop: ui.spacing.xs,
    },

    addBox: {
      ...cardSurface,
      marginBottom: ui.spacing.md,
      gap: ui.spacing.sm,
    },
    input: {
      backgroundColor: colors.bg,
      color: colors.textPrimary,
      padding: 12,
      borderRadius: ui.radius.button,
      borderWidth: 1,
      borderColor: withAlpha(colors.border, 0.32),
      fontSize: 14,
      fontWeight: "500",
    },
    inputFocused: {
      borderColor: withAlpha(colors.accentPrimary, 0.55),
      backgroundColor: withAlpha(colors.surface2, 0.82),
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.12,
      shadowRadius: 4,
    },
    smallLabel: { color: colors.textSecondary, fontWeight: "700", fontSize: 12, letterSpacing: 0.2 },

    pickerRow: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
    pillPick: {
      paddingVertical: 9,
      paddingHorizontal: 11,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: withAlpha(colors.border, 0.32),
      backgroundColor: colors.bg,
    },
    pillPickActive: { backgroundColor: withAlpha(colors.accentPrimary, 0.12), borderColor: withAlpha(colors.accentPrimary, 0.38) },
    pillPickText: { color: colors.textSecondary, fontWeight: "800", fontSize: 12 },
    pillPickTextActive: { color: colors.textPrimary, fontWeight: "900" },

    addBtn: {
      backgroundColor: colors.accentPrimary,
      padding: 13,
      borderRadius: ui.radius.button,
      alignItems: "center",
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.16,
      shadowRadius: 8,
    },
    addBtnText: { color: colors.textPrimary, fontWeight: "900", fontSize: 14 },

    editSheetModalRoot: {
      flex: 1,
      justifyContent: "flex-end",
    },
    editSheetBackdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    editSheetKeyboardWrap: {
      justifyContent: "flex-end",
    },
    editSheetContainer: {
      width: "100%",
      maxHeight: "85%",
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      borderWidth: 1,
      borderBottomWidth: 0,
      overflow: "hidden",
    },
    editSheetHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderBottomWidth: 1,
    },
    editSheetTitle: {
      fontSize: 20,
      lineHeight: 24,
      fontWeight: "900",
      letterSpacing: 0.3,
    },
    editSheetCloseButton: {
      width: 32,
      height: 32,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
    },
    editSheetCloseText: {
      fontSize: 22,
      lineHeight: 22,
      fontWeight: "500",
      marginTop: -2,
    },
    editSheetScroll: {
      flexGrow: 0,
    },
    editSheetFormContent: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 24,
      gap: 14,
    },
    editSheetFieldBlock: {
      gap: 8,
    },
    editSheetLabel: {
      fontSize: 13,
      lineHeight: 16,
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    editSheetInput: {
      minHeight: 48,
      borderRadius: ui.radius.button,
      paddingHorizontal: 12,
      paddingVertical: 12,
      borderWidth: 0,
      fontSize: 15,
      fontWeight: "500",
    },
    editSheetChipRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      rowGap: 8,
    },
    editSheetDifficultyRow: {
      flexDirection: "row",
      gap: 8,
    },
    editSheetChip: {
      width: "32%",
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 10,
      minHeight: 40,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
    },
    editSheetDifficultyChip: {
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 10,
      minHeight: 40,
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
    },
    editSheetChipText: {
      fontSize: 13,
      lineHeight: 16,
      fontWeight: "800",
    },
    editSheetActionBar: {
      borderTopWidth: 1,
      paddingHorizontal: 16,
      paddingVertical: 12,
      paddingBottom: 16,
    },
    editSheetPrimaryButton: {
      minHeight: 52,
      borderRadius: ui.radius.button,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    editSheetPrimaryButtonText: {
      fontSize: 15,
      lineHeight: 19,
      fontWeight: "900",
      letterSpacing: 0.25,
    },

    list: { gap: 0, marginBottom: ui.spacing.md },
    questCard: {
      backgroundColor: "transparent",
      borderBottomWidth: 1,
      borderRadius: 0,
      borderColor: withAlpha(colors.border, 0.4),
      paddingVertical: ui.spacing.xs,
      paddingHorizontal: ui.spacing.xs,
      position: "relative",
      overflow: "hidden",
    },
    questContract: {
      backgroundColor: withAlpha(colors.accentPrimary, 0.045),
      borderBottomColor: withAlpha(colors.accentPrimary, 0.28),
    },
    questContractRail: {
      position: "absolute",
      left: 0,
      top: 8,
      bottom: 8,
      width: 3,
      borderRadius: 999,
      backgroundColor: withAlpha(colors.accentPrimary, 0.78),
    },
    questCompletionFlashOverlay: {
      ...StyleSheet.absoluteFillObject,
      borderRadius: 0,
    },
    questDivider: {
      height: 1,
      backgroundColor: withAlpha(colors.border, 0.42),
      marginVertical: 1,
    },
    questHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: ui.spacing.xs,
      paddingHorizontal: ui.spacing.xs,
      paddingVertical: 6,
    },
    questCompleteToggle: {
      width: 24,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 1,
    },
    questCompleteIconWrap: {
      width: 20,
      height: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    questCompleteAnimatedCheck: {
      position: "absolute",
      alignItems: "center",
      justifyContent: "center",
    },
    questHeaderMain: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: ui.spacing.xs,
    },
    questHeaderPressed: {
      opacity: 0.82,
    },
    questMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: ui.spacing.xs,
      marginTop: ui.spacing.xxs,
    },
    questMetaDifficulty: {
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 0.6,
      textTransform: "uppercase",
      opacity: 0.82,
    },
    questMetaCategory: {
      fontSize: 11,
      fontWeight: "600",
      lineHeight: 15,
      opacity: 0.76,
    },
    questMetaSingleLine: {
      marginTop: 2,
      fontSize: 11,
      fontWeight: "600",
      lineHeight: 15,
      opacity: 0.78,
    },
    questStatusStack: {
      alignItems: "flex-end",
      gap: 6,
      marginLeft: ui.spacing.xs,
    },
    statusPill: {
      paddingVertical: 2,
      paddingHorizontal: 6,
      borderRadius: 999,
      fontSize: 9,
      fontWeight: "900",
      letterSpacing: 0.3,
      overflow: "hidden",
    },
    statusPillIcon: {
      paddingVertical: 2,
      paddingHorizontal: 2,
      borderRadius: ui.radius.sm,
      alignItems: "center",
      justifyContent: "center",
    },
    questActionsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: ui.spacing.xs,
      alignItems: "center",
      paddingTop: 6,
    },
    questActionBtnSubtle: {
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderRadius: 999,
      borderWidth: 1,
      minWidth: 58,
      alignItems: "center",
      justifyContent: "center",
    },
    questActionBtnPrimary: {
      paddingVertical: 5,
      paddingHorizontal: 12,
      borderRadius: 999,
      borderWidth: 1,
      minWidth: 86,
      alignItems: "center",
      justifyContent: "center",
    },
    questActionTextSubtle: { fontWeight: "800", fontSize: 11, letterSpacing: 0.2 },
    questActionTextPrimary: { fontWeight: "800", fontSize: 11, letterSpacing: 0.15 },
    questActionBtn: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 999,
      borderWidth: 1,
    },
    questActionText: { fontWeight: "900", fontSize: 12 },
    questDone: {
      opacity: 0.82,
      borderColor: withAlpha(colors.accentPrimary, 0.38),
    },
    questDoneBar: {
      height: 1,
      borderRadius: 999,
      backgroundColor: `${colors.accentSecondary}55`,
      marginBottom: ui.spacing.xs,
    },
    questTitle: { color: colors.textPrimary, fontSize: 15, fontWeight: "800" },
    questTitleDone: { textDecorationLine: "line-through", opacity: 0.6 },
    questMeta: { color: colors.textSecondary, marginTop: 6, fontSize: 12 },

    rightStack: { gap: 9, alignItems: "flex-end" },

    completeBtn: {
      backgroundColor: colors.accentPrimary,
      paddingVertical: 9,
      paddingHorizontal: 12,
      borderRadius: ui.radius.button,
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.16,
      shadowRadius: 4,
    },
    completeText: { color: colors.textPrimary, fontWeight: "900", fontSize: 11 },

    doneBadge: {
      backgroundColor: `${colors.accentSecondary}1A`,
      borderWidth: 1,
      borderColor: withAlpha(colors.accentSecondary, 0.42),
      paddingVertical: 9,
      paddingHorizontal: 11,
      borderRadius: ui.radius.button,
    },
    doneText: { color: colors.accentSecondary, fontWeight: "900", fontSize: 11 },

    editBtn: {
      backgroundColor: colors.bg,
      borderWidth: 1,
      borderColor: withAlpha(colors.border, 0.3),
      paddingVertical: 7,
      paddingHorizontal: 11,
      borderRadius: ui.radius.button,
    },
    editText: { color: colors.textPrimary, fontWeight: "900", fontSize: 11 },

    pinBtn: {
      backgroundColor: colors.bg,
      borderWidth: 1,
      borderColor: withAlpha(colors.border, 0.3),
      paddingVertical: 7,
      paddingHorizontal: 11,
      borderRadius: ui.radius.button,
    },
    pinText: { color: colors.textSecondary, fontWeight: "900", fontSize: 11 },

    deleteBtn: {
      backgroundColor: colors.bg,
      borderWidth: 1,
      borderColor: withAlpha(colors.accentPrimary, 0.35),
      paddingVertical: 7,
      paddingHorizontal: 11,
      borderRadius: ui.radius.button,
    },
    deleteText: { color: colors.accentPrimary, fontWeight: "900", fontSize: 11 },

    btnPressed: {
      opacity: 0.7,
      transform: [{ scale: 0.95 }],
    },

    grid: { gap: 12 },
    card: {
      ...cardSurface,
      padding: ui.spacing.card,
      borderRadius: ui.radius.card,
    },
    cardSecondary: {
      ...secondaryCardSurface,
      padding: ui.spacing.md,
    },
    focusList: { marginTop: ui.spacing.sm },
    focusRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: ui.spacing.sm,
      paddingHorizontal: 0,
      backgroundColor: "transparent",
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "transparent",
    },
    focusLabel: {
      ...ui.typography.body,
      color: colors.textPrimary,
      fontWeight: "700",
      opacity: 0.9,
    },
    focusMeta: {
      ...ui.typography.caption,
      marginTop: 0,
      color: withAlpha(colors.textSecondary, 0.88),
      fontWeight: "700",
      textAlign: "right",
    },
    focusDivider: {
      height: 1,
      backgroundColor: withAlpha(colors.border, 0.28),
    },
    cardTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "baseline",
      marginBottom: 9,
    },
    cardTitle: { ...ui.typography.heading, color: colors.textPrimary, fontSize: 18 },
    drSystemSubhead: {
      color: colors.textSecondary,
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 0.3,
      textTransform: "uppercase",
      marginTop: 14,
      marginBottom: 8,
    },
    drSystemTopRow: {
      backgroundColor: withAlpha(colors.accentPrimary, 0.07),
      borderWidth: ui.border.width,
      borderColor: withAlpha(colors.accentPrimary, 0.22),
      borderRadius: ui.radius.md,
      paddingVertical: ui.spacing.xs,
      paddingHorizontal: ui.spacing.sm,
      marginBottom: ui.spacing.sm,
    },
    drSystemTopText: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: "700",
      lineHeight: 18,
    },
    drSystemRow: {
      ...compactTileSurface,
      borderWidth: ui.border.width,
      borderRadius: ui.radius.md,
      paddingVertical: ui.spacing.xs,
      paddingHorizontal: ui.spacing.sm,
      marginTop: 6,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    drSystemRowActive: {
      borderColor: withAlpha(colors.accentPrimary, 0.35),
      backgroundColor: withAlpha(colors.accentPrimary, 0.09),
    },
    statsSectionFlat: {
      marginBottom: ui.spacing.md,
    },
    analyticsRow: {
      flexDirection: "row",
      gap: ui.spacing.xs,
      marginBottom: ui.spacing.md,
    },
    analyticsTile: {
      ...compactTileSurface,
      flex: 1,
      paddingVertical: ui.spacing.xs,
      paddingHorizontal: ui.spacing.xs,
    },
    analyticsLabel: {
      ...ui.typography.caption,
      color: colors.textSecondary,
      fontSize: 9,
      letterSpacing: 0.65,
    },
    analyticsValue: {
      ...ui.typography.mono,
      color: colors.textPrimary,
      fontSize: 15,
      marginTop: 2,
    },
    trendCard: {
      ...cardSurface,
      borderColor: withAlpha(colors.border, 0.24),
      backgroundColor: withAlpha(colors.surface2, 0.72),
      borderRadius: ui.radius.card,
      paddingHorizontal: ui.spacing.md,
      paddingVertical: ui.spacing.md,
      marginBottom: ui.spacing.md,
      gap: ui.spacing.xs,
    },
    trendHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: ui.spacing.sm,
    },
    trendTitle: {
      color: colors.textPrimary,
      fontSize: 17,
      lineHeight: 21,
      fontWeight: "900",
    },
    trendMeta: {
      color: withAlpha(colors.textSecondary, 0.82),
      fontSize: 10,
      lineHeight: 13,
      fontWeight: "800",
      letterSpacing: 0.45,
      textTransform: "uppercase",
    },
    trendBarRail: {
      height: 58,
      flexDirection: "row",
      alignItems: "flex-end",
      gap: 6,
      marginTop: ui.spacing.xs,
    },
    trendBar: {
      flex: 1,
      minHeight: 4,
      borderRadius: 999,
      backgroundColor: colors.accentPrimary,
      opacity: 0.88,
    },
    streakGrid: {
      flexDirection: "row",
      gap: ui.spacing.xs,
      marginBottom: ui.spacing.md,
    },
    streakTile: {
      ...compactTileSurface,
      flex: 1,
      paddingHorizontal: ui.spacing.xs,
      paddingVertical: ui.spacing.sm,
      minWidth: 0,
    },
    streakValue: {
      color: colors.textPrimary,
      fontSize: 24,
      lineHeight: 28,
      fontWeight: "900",
    },
    streakLabel: {
      color: withAlpha(colors.textSecondary, 0.8),
      fontSize: 9,
      lineHeight: 12,
      fontWeight: "800",
      letterSpacing: 0.45,
      textTransform: "uppercase",
      marginTop: 2,
    },
    statsSectionDivider: {
      height: 1,
      backgroundColor: withAlpha(colors.border, 0.32),
      marginTop: ui.spacing.sm,
      marginBottom: ui.spacing.md,
    },
    tableHeaderRow: {
      flexDirection: "row",
      paddingVertical: ui.spacing.xs,
      borderBottomWidth: 1,
      borderBottomColor: withAlpha(colors.border, 0.48),
      marginBottom: ui.spacing.xxs,
    },
    tableHeaderText: {
      ...ui.typography.caption,
      color: withAlpha(colors.textSecondary, 0.9),
      fontSize: 10,
      letterSpacing: 0.7,
    },
    tableRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: ui.spacing.xs,
      borderBottomWidth: 1,
      borderBottomColor: withAlpha(colors.border, 0.28),
    },
    tableCell: {
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: "700",
    },
    tableCellSubtext: {
      color: withAlpha(colors.textSecondary, 0.78),
      fontSize: 10,
      lineHeight: 13,
      fontWeight: "700",
      marginTop: 1,
    },
    drRankRow: {
      backgroundColor: colors.surface,
      borderWidth: 0,
      borderRadius: ui.radius.md,
      paddingVertical: ui.spacing.sm,
      paddingHorizontal: ui.spacing.sm,
      marginTop: ui.spacing.sm,
      minHeight: 52,
      flexDirection: "row",
      alignItems: "center",
      shadowColor: colors.text,
      shadowOffset: ui.shadow.soft.shadowOffset,
      shadowOpacity: 0.07,
      shadowRadius: ui.shadow.soft.shadowRadius,
      elevation: ui.shadow.soft.elevation,
    },
    drRankRowActive: {
      backgroundColor: withAlpha(colors.accentPrimary, 0.1),
    },
    drRankAccentBar: {
      width: 3,
      alignSelf: "stretch",
      borderRadius: 999,
      marginRight: ui.spacing.sm,
      backgroundColor: colors.accentPrimary,
    },
    drRankRowContent: {
      flex: 1,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    drSystemRankName: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: "700",
    },
    drSystemRankRange: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: "800",
    },
    drSystemRuleLabel: {
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: "700",
    },
    drSystemRuleDelta: {
      fontSize: 12,
      fontWeight: "900",
    },
    level: { fontSize: 14, fontWeight: "700", color: colors.accentPrimary, letterSpacing: 0.2 },
    xpText: { color: colors.textSecondary, marginBottom: 9, fontSize: 12, fontWeight: "500" },
    barTrack: {
      height: 11,
      borderRadius: 999,
      backgroundColor: colors.bg,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: withAlpha(colors.border, 0.3),
    },
    barFill: { height: "100%", backgroundColor: colors.accentPrimary, borderRadius: 999 },

    difficultyEasy: {
      backgroundColor: `${colors.accentTertiary}1A`,
      borderWidth: 1,
      borderColor: withAlpha(colors.accentTertiary, 0.45),
      paddingVertical: 5,
      paddingHorizontal: 9,
      borderRadius: 999,
    },
    difficultyMedium: {
      backgroundColor: `${colors.accentSecondary}1A`,
      borderWidth: 1,
      borderColor: withAlpha(colors.accentSecondary, 0.45),
      paddingVertical: 5,
      paddingHorizontal: 9,
      borderRadius: 999,
    },
    difficultyHard: {
      backgroundColor: `${colors.accentPrimary}1A`,
      borderWidth: 1,
      borderColor: withAlpha(colors.accentPrimary, 0.45),
      paddingVertical: 5,
      paddingHorizontal: 9,
      borderRadius: 999,
    },
    difficultyText: { fontWeight: "900", fontSize: 10, color: colors.textPrimary, letterSpacing: 0.2 },

    // Achievements
    achievementSection: { marginBottom: 28, marginTop: 28 },
    achievementHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    achievementProgress: {
      backgroundColor: withAlpha(colors.surface2, 0.7),
      borderRadius: 999,
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: withAlpha(colors.border, 0.24),
    },
    achievementProgressText: { color: colors.accentPrimary, fontWeight: "800", fontSize: 13 },
    achievementGrid: { gap: 12 },
    achievementBadge: {
      ...cardSurface,
      padding: ui.spacing.md,
      alignItems: "center",
      gap: 8,
    },
    achievementUnlocked: {
      backgroundColor: `${colors.accentSecondary}1A`,
      borderColor: withAlpha(colors.accentSecondary, 0.38),
      shadowColor: colors.accentSecondary,
      shadowRadius: 6,
    },
    achievementLocked: {
      opacity: 0.4,
      backgroundColor: colors.bg,
      borderColor: withAlpha(colors.border, 0.24),
    },
    achievementIcon: { fontSize: 32 },
    achievementName: { color: colors.textPrimary, fontWeight: "900", fontSize: 13, textAlign: "center" },
    achievementDesc: { color: colors.textSecondary, fontWeight: "600", fontSize: 12, textAlign: "center" },
    achievementDate: { color: colors.accentSecondary, fontWeight: "800", fontSize: 11, marginTop: 4 },

    hint: { marginTop: 24, color: colors.textSecondary, lineHeight: 20, fontSize: 13 },
    homeHintCard: {
      marginTop: ui.spacing.sm,
      paddingVertical: ui.spacing.xs,
      paddingHorizontal: 0,
      borderTopWidth: 1,
      borderTopColor: withAlpha(colors.border, 0.28),
    },
    homeHintText: {
      color: withAlpha(colors.textSecondary, 0.84),
      lineHeight: ui.typography.body.lineHeight,
      fontSize: ui.typography.body.fontSize,
      fontWeight: "600",
      opacity: 0.9,
    },
  });
};
