import { StyleSheet } from "react-native";
import type { ThemeColors } from "./utils/themeContext";

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.bg },
    screen: { flex: 1, backgroundColor: colors.bg },
    bgArt: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    sectionBand: {
      marginHorizontal: -16,
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    sectionBandTight: {
      paddingBottom: 8,
    },
    container: { padding: 16, paddingBottom: 24 },

    title: { fontSize: 26, fontWeight: "900", color: colors.accentPrimary, marginBottom: 16, letterSpacing: 0.3 },

    topRow: { flexDirection: "row", gap: 10, marginBottom: 18, flexWrap: "wrap" },
    pill: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderWidth: 1.5,
      borderColor: colors.border,
      flex: 1,
      minWidth: 110,
      shadowColor: "rgba(0,0,0,0.3)",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 4,
    },
    pillLabel: { color: colors.textSecondary, fontSize: 10, fontWeight: "600", letterSpacing: 0.3, textTransform: "uppercase" },
    pillValue: { color: colors.accentPrimary, fontSize: 15, fontWeight: "900", marginTop: 3, letterSpacing: 0.3 },

    row: { flexDirection: "row", gap: 10, marginBottom: 18, flexWrap: "wrap" },
    btn: {
      backgroundColor: colors.surface,
      paddingVertical: 11,
      paddingHorizontal: 14,
      borderRadius: 11,
      borderWidth: 1.5,
      borderColor: colors.border,
      shadowColor: "rgba(0,0,0,0.2)",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 3,
    },
    btnDanger: {
      backgroundColor: colors.bg,
      paddingVertical: 11,
      paddingHorizontal: 14,
      borderRadius: 11,
      borderWidth: 1.5,
      borderColor: colors.accentPrimary,
      shadowColor: "rgba(0,0,0,0.2)",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 3,
    },
    btnText: { color: colors.textPrimary, fontWeight: "800", fontSize: 12 },

    sectionRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 14,
      marginTop: 18,
    },
    section: { fontSize: 18, fontWeight: "900", color: colors.textPrimary, letterSpacing: 0.2 },
    link: { color: colors.accentPrimary, fontWeight: "900", fontSize: 12 },

    addBox: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1.5,
      borderColor: colors.border,
      marginBottom: 16,
      gap: 12,
      shadowColor: "rgba(0,0,0,0.3)",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 6,
    },
    input: {
      backgroundColor: colors.bg,
      color: colors.textPrimary,
      padding: 12,
      borderRadius: 11,
      borderWidth: 1.5,
      borderColor: colors.border,
      fontSize: 14,
      fontWeight: "500",
    },
    inputFocused: {
      borderColor: colors.accentPrimary,
      backgroundColor: colors.surface,
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    smallLabel: { color: colors.textSecondary, fontWeight: "700", fontSize: 11, letterSpacing: 0.2 },

    pickerRow: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
    pillPick: {
      paddingVertical: 9,
      paddingHorizontal: 11,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.bg,
    },
    pillPickActive: { backgroundColor: colors.accentPrimary, borderColor: colors.accentPrimary },
    pillPickText: { color: colors.textSecondary, fontWeight: "800", fontSize: 11 },
    pillPickTextActive: { color: colors.textPrimary, fontWeight: "900" },

    addBtn: {
      backgroundColor: colors.accentPrimary,
      padding: 13,
      borderRadius: 11,
      alignItems: "center",
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
    },
    addBtnText: { color: colors.textPrimary, fontWeight: "900", fontSize: 13 },

    list: { gap: 11, marginBottom: 18 },
    questCard: {
      flexDirection: "column",
      alignItems: "stretch",
      gap: 12,
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 14,
      borderWidth: 1.5,
      borderColor: colors.border,
      shadowColor: "rgba(0,0,0,0.2)",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 4,
    },
    questHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    questMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginTop: 4,
    },
    questStatusStack: {
      alignItems: "flex-end",
      gap: 6,
    },
    statusPill: {
      paddingVertical: 4,
      paddingHorizontal: 8,
      borderRadius: 999,
      fontSize: 10,
      fontWeight: "900",
    },
    statusPillIcon: {
      paddingVertical: 4,
      paddingHorizontal: 6,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
    },
    questActionsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      alignItems: "center",
    },
    questActionBtn: {
      paddingVertical: 7,
      paddingHorizontal: 10,
      borderRadius: 8,
      borderWidth: 1.5,
    },
    questActionText: { fontWeight: "900", fontSize: 11 },
    questDone: { opacity: 0.5, backgroundColor: colors.bg },
    questTitle: { color: colors.textPrimary, fontSize: 15, fontWeight: "900" },
    questTitleDone: { textDecorationLine: "line-through", opacity: 0.6 },
    questMeta: { color: colors.textSecondary, marginTop: 5, fontSize: 11 },

    rightStack: { gap: 9, alignItems: "flex-end" },

    completeBtn: {
      backgroundColor: colors.accentPrimary,
      paddingVertical: 9,
      paddingHorizontal: 12,
      borderRadius: 9,
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
    },
    completeText: { color: colors.textPrimary, fontWeight: "900", fontSize: 11 },

    doneBadge: {
      backgroundColor: `${colors.accentSecondary}1A`,
      borderWidth: 1.5,
      borderColor: colors.accentSecondary,
      paddingVertical: 9,
      paddingHorizontal: 11,
      borderRadius: 9,
    },
    doneText: { color: colors.accentSecondary, fontWeight: "900", fontSize: 11 },

    editBtn: {
      backgroundColor: colors.bg,
      borderWidth: 1.5,
      borderColor: colors.border,
      paddingVertical: 7,
      paddingHorizontal: 11,
      borderRadius: 9,
    },
    editText: { color: colors.textPrimary, fontWeight: "900", fontSize: 11 },

    pinBtn: {
      backgroundColor: colors.bg,
      borderWidth: 1.5,
      borderColor: colors.border,
      paddingVertical: 7,
      paddingHorizontal: 11,
      borderRadius: 9,
    },
    pinText: { color: colors.textSecondary, fontWeight: "900", fontSize: 11 },
    
    deleteBtn: {
      backgroundColor: colors.bg,
      borderWidth: 1.5,
      borderColor: colors.accentPrimary,
      paddingVertical: 7,
      paddingHorizontal: 11,
      borderRadius: 9,
    },
    deleteText: { color: colors.accentPrimary, fontWeight: "900", fontSize: 11 },

  btnPressed: {
    opacity: 0.7,
    transform: [{ scale: 0.95 }],
  },

    grid: { gap: 12 },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 14,
      borderWidth: 1.5,
      borderColor: colors.border,
      shadowColor: "rgba(0,0,0,0.2)",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 4,
    },
    cardTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "baseline",
      marginBottom: 9,
    },
    cardTitle: { fontSize: 16, fontWeight: "900", color: colors.textPrimary, letterSpacing: 0.2 },
    level: { fontSize: 14, fontWeight: "700", color: colors.accentPrimary, letterSpacing: 0.2 },
    xpText: { color: colors.textSecondary, marginBottom: 9, fontSize: 12, fontWeight: "500" },
    barTrack: {
      height: 11,
      borderRadius: 5.5,
      backgroundColor: colors.bg,
      overflow: "hidden",
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    barFill: { height: "100%", backgroundColor: colors.accentPrimary, borderRadius: 5.5 },

    difficultyEasy: {
      backgroundColor: `${colors.accentTertiary}1A`,
      borderWidth: 2,
      borderColor: colors.accentTertiary,
      paddingVertical: 5,
      paddingHorizontal: 9,
      borderRadius: 7,
      shadowColor: colors.accentTertiary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
    },
    difficultyMedium: {
      backgroundColor: `${colors.accentSecondary}1A`,
      borderWidth: 2,
      borderColor: colors.accentSecondary,
      paddingVertical: 5,
      paddingHorizontal: 9,
      borderRadius: 7,
      shadowColor: colors.accentSecondary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
    },
    difficultyHard: {
      backgroundColor: `${colors.accentPrimary}1A`,
      borderWidth: 2,
      borderColor: colors.accentPrimary,
      paddingVertical: 5,
      paddingHorizontal: 9,
      borderRadius: 7,
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
    },
    difficultyText: { fontWeight: "900", fontSize: 10, color: colors.textPrimary, letterSpacing: 0.2 },

    // Achievements
    achievementSection: { marginBottom: 28, marginTop: 28 },
    achievementHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    achievementProgress: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    achievementProgressText: { color: colors.accentPrimary, fontWeight: "800", fontSize: 13 },
    achievementGrid: { gap: 12 },
    achievementBadge: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 16,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: "center",
      gap: 8,
      shadowColor: "rgba(0,0,0,0.2)",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 4,
    },
    achievementUnlocked: {
      backgroundColor: `${colors.accentSecondary}1A`,
      borderColor: colors.accentSecondary,
      shadowColor: colors.accentSecondary,
      shadowRadius: 6,
    },
    achievementLocked: {
      opacity: 0.4,
      backgroundColor: colors.bg,
      borderColor: colors.border,
    },
    achievementIcon: { fontSize: 32 },
    achievementName: { color: colors.textPrimary, fontWeight: "900", fontSize: 13, textAlign: "center" },
    achievementDesc: { color: colors.textSecondary, fontWeight: "600", fontSize: 12, textAlign: "center" },
    achievementDate: { color: colors.accentSecondary, fontWeight: "800", fontSize: 11, marginTop: 4 },

    hint: { marginTop: 24, color: colors.textSecondary, lineHeight: 20, fontSize: 13 },
  });
