import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#080c12" },
  screen: { flex: 1, backgroundColor: "#06080d" },
  bgArt: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  sectionBand: {
    marginHorizontal: -16,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  sectionBandTight: {
    paddingBottom: 8,
  },
  container: { padding: 16, paddingBottom: 24 },

  title: { fontSize: 26, fontWeight: "900", color: "#00d9ff", marginBottom: 16, letterSpacing: 0.3 },

  topRow: { flexDirection: "row", gap: 10, marginBottom: 18, flexWrap: "wrap" },
  pill: {
    backgroundColor: "#141d2a",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1.5,
    borderColor: "#1f2a3c",
    flex: 1,
    minWidth: 110,
    shadowColor: "rgba(0,0,0,0.3)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  pillLabel: { color: "#8fa3b0", fontSize: 10, fontWeight: "600", letterSpacing: 0.3, textTransform: "uppercase" },
  pillValue: { color: "#00d9ff", fontSize: 15, fontWeight: "900", marginTop: 3, letterSpacing: 0.3 },

  row: { flexDirection: "row", gap: 10, marginBottom: 18, flexWrap: "wrap" },
  btn: {
    backgroundColor: "#1a2635",
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: "#2a3a4a",
    shadowColor: "rgba(0,0,0,0.2)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 3,
  },
  btnDanger: {
    backgroundColor: "#3a1a20",
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: "#5a2a36",
    shadowColor: "rgba(0,0,0,0.2)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 3,
  },
  btnText: { color: "white", fontWeight: "800", fontSize: 12 },

  sectionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
    marginTop: 18,
  },
  section: { fontSize: 18, fontWeight: "900", color: "#ffffff", letterSpacing: 0.2 },
  link: { color: "#00d9ff", fontWeight: "900", fontSize: 12 },

  addBox: {
    backgroundColor: "#141d2a",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1.5,
    borderColor: "#1f2a3c",
    marginBottom: 16,
    gap: 12,
    shadowColor: "rgba(0,0,0,0.3)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
  },
  input: {
    backgroundColor: "#0a0e14",
    color: "white",
    padding: 12,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: "#1f2a3c",
    fontSize: 14,
    fontWeight: "500",
  },
  inputFocused: {
    borderColor: "#00d9ff",
    backgroundColor: "#0f1419",
    shadowColor: "rgba(0,217,255,0.2)",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  smallLabel: { color: "#8fa3b0", fontWeight: "700", fontSize: 11, letterSpacing: 0.2 },

  pickerRow: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  pillPick: {
    paddingVertical: 9,
    paddingHorizontal: 11,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#1f2a3c",
    backgroundColor: "#0a0e14",
  },
  pillPickActive: { backgroundColor: "#00d9ff", borderColor: "#00d9ff" },
  pillPickText: { color: "#b9c0cc", fontWeight: "800", fontSize: 11 },
  pillPickTextActive: { color: "#0a0e14", fontWeight: "900" },

  addBtn: {
    backgroundColor: "#00d9ff",
    padding: 13,
    borderRadius: 11,
    alignItems: "center",
    shadowColor: "rgba(0,217,255,0.3)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 8,
  },
  addBtnText: { color: "#0a0e14", fontWeight: "900", fontSize: 13 },

  list: { gap: 11, marginBottom: 18 },
  questCard: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 12,
    backgroundColor: "#141d2a",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1.5,
    borderColor: "#1f2a3c",
    shadowColor: "rgba(0,0,0,0.2)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  questHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  questMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  questStatusStack: {
    alignItems: "flex-end",
    gap: 6,
  },
  statusPill: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 999,
    fontSize: 10,
    fontWeight: "900",
  },
  statusPillIcon: {
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  questActionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
  },
  questActionBtn: {
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1.5,
  },
  questActionText: { fontWeight: "900", fontSize: 11 },
  questDone: { opacity: 0.5, backgroundColor: "#0a0e14" },
  questTitle: { color: "#ffffff", fontSize: 15, fontWeight: "900" },
  questTitleDone: { textDecorationLine: "line-through", opacity: 0.6 },
  questMeta: { color: "#8fa3b0", marginTop: 5, fontSize: 11 },

  rightStack: { gap: 9, alignItems: "flex-end" },

  completeBtn: {
    backgroundColor: "#00d9ff",
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 9,
    shadowColor: "rgba(0,217,255,0.3)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  completeText: { color: "#0a0e14", fontWeight: "900", fontSize: 11 },

  doneBadge: {
    backgroundColor: "#0a1a10",
    borderWidth: 1.5,
    borderColor: "#00ff88",
    paddingVertical: 9,
    paddingHorizontal: 11,
    borderRadius: 9,
  },
  doneText: { color: "#00ff88", fontWeight: "900", fontSize: 11 },

  editBtn: {
    backgroundColor: "#1a2a35",
    borderWidth: 1.5,
    borderColor: "#2a4a5a",
    paddingVertical: 7,
    paddingHorizontal: 11,
    borderRadius: 9,
  },
  editText: { color: "#00d9ff", fontWeight: "900", fontSize: 11 },

  pinBtn: {
    backgroundColor: "#142030",
    borderWidth: 1.5,
    borderColor: "#2a3a4a",
    paddingVertical: 7,
    paddingHorizontal: 11,
    borderRadius: 9,
  },
  pinText: { color: "#8fa3b0", fontWeight: "900", fontSize: 11 },
  
  deleteBtn: {
    backgroundColor: "#2a1a1a",
    borderWidth: 1.5,
    borderColor: "#4a2a2a",
    paddingVertical: 7,
    paddingHorizontal: 11,
    borderRadius: 9,
  },
  deleteText: { color: "#ff6b6b", fontWeight: "900", fontSize: 11 },

  btnPressed: {
    opacity: 0.7,
    transform: [{ scale: 0.95 }],
  },

  grid: { gap: 12 },
  card: {
    backgroundColor: "#141d2a",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1.5,
    borderColor: "#1f2a3c",
    shadowColor: "rgba(0,0,0,0.2)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginBottom: 9,
  },
  cardTitle: { fontSize: 16, fontWeight: "900", color: "#ffffff", letterSpacing: 0.2 },
  level: { fontSize: 14, fontWeight: "700", color: "#00d9ff", letterSpacing: 0.2 },
  xpText: { color: "#8fa3b0", marginBottom: 9, fontSize: 12, fontWeight: "500" },
  barTrack: {
    height: 11,
    borderRadius: 5.5,
    backgroundColor: "#0a0e14",
    overflow: "hidden",
    borderWidth: 1.5,
    borderColor: "#1f2a3c",
  },
  barFill: { height: "100%", backgroundColor: "#00d9ff", borderRadius: 5.5 },

  difficultyEasy: {
    backgroundColor: "#0a1a10",
    borderWidth: 2,
    borderColor: "#00ff88",
    paddingVertical: 5,
    paddingHorizontal: 9,
    borderRadius: 7,
    shadowColor: "rgba(0,255,136,0.2)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 3,
  },
  difficultyMedium: {
    backgroundColor: "#2a1f05",
    borderWidth: 2,
    borderColor: "#ffaa00",
    paddingVertical: 5,
    paddingHorizontal: 9,
    borderRadius: 7,
    shadowColor: "rgba(255,170,0,0.2)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 3,
  },
  difficultyHard: {
    backgroundColor: "#2a0a0a",
    borderWidth: 2,
    borderColor: "#ff4444",
    paddingVertical: 5,
    paddingHorizontal: 9,
    borderRadius: 7,
    shadowColor: "rgba(255,68,68,0.2)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 3,
  },
  difficultyText: { fontWeight: "900", fontSize: 10, color: "white", letterSpacing: 0.2 },

  // Achievements
  achievementSection: { marginBottom: 28, marginTop: 28 },
  achievementHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  achievementProgress: {
    backgroundColor: "#141d2a",
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1.5,
    borderColor: "#1f2a3c",
  },
  achievementProgressText: { color: "#00d9ff", fontWeight: "800", fontSize: 13 },
  achievementGrid: { gap: 12 },
  achievementBadge: {
    backgroundColor: "#141d2a",
    borderRadius: 14,
    padding: 16,
    borderWidth: 1.5,
    borderColor: "#1f2a3c",
    alignItems: "center",
    gap: 8,
    shadowColor: "rgba(0,0,0,0.2)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  achievementUnlocked: {
    backgroundColor: "#2a1f05",
    borderColor: "#ffaa00",
    shadowColor: "rgba(255,170,0,0.2)",
    shadowRadius: 6,
  },
  achievementLocked: {
    opacity: 0.4,
    backgroundColor: "#0a0e14",
    borderColor: "#1f2a3c",
  },
  achievementIcon: { fontSize: 32 },
  achievementName: { color: "#ffffff", fontWeight: "900", fontSize: 13, textAlign: "center" },
  achievementDesc: { color: "#8fa3b0", fontWeight: "600", fontSize: 12, textAlign: "center" },
  achievementDate: { color: "#00ff88", fontWeight: "800", fontSize: 11, marginTop: 4 },

  hint: { marginTop: 24, color: "#5a6a7a", lineHeight: 20, fontSize: 13 },
});
